k9s:
  refreshRate: 2
  headless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: overwatch-prod
  currentCluster: overwatch-prod
  clusters:
    overwatch-prod:
      namespace:
        active: overwatch
        favorites:
        - all
        - overwatch
        - ingress-basic
        - elk
        - default
      view:
        active: pods elk
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
